---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: mlflow

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: github-runner-full-access
  namespace: mlflow
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  - jobs/status
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: github-runner-view
  namespace: mlflow
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: mlflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-runner-full-access
