name: run_mlflow_experiment

on:
  workflow_dispatch:
    inputs:
      alpha:
        description: 'alpha value'     
        required: true
        default: '0.4'
      l1_ratio:
        description: 'l1_ratio value'
        required: true
        default: '0.1'
      mlflow_tracking_uri:
        description: 'FQDN of the MLFLOW server'
        required: true

jobs:
  run_mlflow_project:
    runs-on: ubuntu-latest
    name: Runs a MLFLOW project in a remote server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      # - name: Run mlflow project remotely
      #   uses: ./actions/run-mlflow-project
      #   with:
      #     alpha: "${{ github.event.inputs.alpha }}"
      #     l1_ratio: "${{ github.event.inputs.l1_ratio }}"
      #     mlflow_tracking_uri: "${{ github.event.inputs.mlflow_tracking_uri }}"
      - name: Run mlflow project remotely
        run: |
          pip install -r requirements.txt
          python run_mlflow_project.py "${{ github.event.inputs.alpha }}" "${{ github.event.inputs.l1_ratio }}" "${{ github.event.inputs.mlflow_tracking_uri }}"
