name: run_mlflow_experiment

on:
  workflow_dispatch:
    inputs:
      alpha:
        description: 'alpha value'     
        required: true
        default: '0.4'
      l1_ratio:
        description: 'l1_ratio value'
        required: true
        default: '0.1'
      mlflow_tracking_uri:
        description: 'FQDN of the MLFLOW server'
        required: true
      kubernetes_service_address:
        description: 'FQDN of the kubernetes service'
        required: true

jobs:
  run_mlflow_project:
    runs-on: ubuntu-latest
    name: Runs a MLFLOW project in a remote server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/thesis-mlflow-project
      - name: Run mlflow project remotely
        run: |
          pip install -r requirements.txt
          export KUBECONFIG=${{ github.workspace }}/kube_config
          export KUBERNETES_SERVICE_HOST="${{ github.event.inputs.kubernetes_service_address }}"
          export KUBERNETES_SERVICE_PORT=80
          export MLFLOW_TRACKING_URI="${{ github.event.inputs.mlflow_tracking_uri }}"
          python run_mlflow_project.py "${{ github.event.inputs.alpha }}" "${{ github.event.inputs.l1_ratio }}"
